# Pytorch tutorial + cheatsheet
> prepared by Shoeb Joarder

In [1]:
import torch

## Torch Tensors

In [2]:
# This is a 1-D Tensor
a = torch.tensor([2, 2, 1])
print(a)

tensor([2, 2, 1])


In [3]:
# This is a 2-D Tensor
b = torch.tensor([[2,1,4], [3,5,4], [1,2,0], [4,3,2]])
print(b)

tensor([[2, 1, 4],
        [3, 5, 4],
        [1, 2, 0],
        [4, 3, 2]])


In [4]:
# The size of the tensor
print(a.shape)
print(b.shape)
print(a.size())
print(a.size())

torch.Size([3])
torch.Size([4, 3])
torch.Size([3])
torch.Size([3])


In [5]:
# Get the height/number of rows of b
print(b.shape[0])

4


In [6]:
c = torch.FloatTensor([[2,1,4], [3,5,4], [1,2,0], [4,3,2]])
# or we can do
# c = torch.tensor([2,2,1], dtype= torch.float)

In [7]:
d = torch.DoubleTensor([[2,1,4], [3,5,4], [1,2,0], [4,3,2]])
# or we can do
# c = torch.tensor([2,2,1], dtype= torch.double)

In [8]:
print(c)
print(c.dtype)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]])
torch.float32


In [9]:
print(d)
print(d.dtype)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]], dtype=torch.float64)
torch.float64


In [10]:
print(c.mean())

tensor(2.5833)


In [11]:
print(d.mean())

tensor(2.5833, dtype=torch.float64)


In [12]:
print(c.std())

tensor(1.5050)


In [13]:
print(d.std())

tensor(1.5050, dtype=torch.float64)


In [14]:
# Reshape b
# Note: IF one of the dimensions is -1, its size can be inferred
print(b.view(-1,1))
print('\n')

print(b.view(12))
print('\n')

print(b.view(-1,4))
print('\n')

print(b.view(3,4))
print('\n')

# Assign b a new shape
b = b.view(1, -1)
print(b)
print(b.shape)
print('\n')

# We can even reshape 3D tensors
# Create a 3D tensor with 2 channels, 3 rows and 4 columns (channels, row, columns)
three_dim = torch.randn(2, 3, 4)
print(three_dim)
print('\n')
print(three_dim.view(2, 12)) # Reshape to 2 rows, 12 columns
print('\n')
print(three_dim.view(2, -1))

tensor([[2],
        [1],
        [4],
        [3],
        [5],
        [4],
        [1],
        [2],
        [0],
        [4],
        [3],
        [2]])


tensor([2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2])


tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])


tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])


tensor([[2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2]])
torch.Size([1, 12])


tensor([[[ 0.5125,  0.1649,  0.9801,  1.0055],
         [ 0.0105, -1.0845,  0.7614, -1.3231],
         [-0.6040, -0.0470, -0.9427,  1.5669]],

        [[ 0.3275,  1.1690, -0.5994, -0.0023],
         [ 1.0912, -2.1684,  0.1553, -1.6559],
         [ 0.3436, -1.3831, -0.3699,  1.1546]]])


tensor([[ 0.5125,  0.1649,  0.9801,  1.0055,  0.0105, -1.0845,  0.7614, -1.3231,
         -0.6040, -0.0470, -0.9427,  1.5669],
        [ 0.3275,  1.1690, -0.5994, -0.0023,  1.0912, -2.1684,  0.1553, -1.6559,
          0.3436, -1.3831, -0.3699,  1.1546]])


tensor([[ 0.5125,  0.1649,  0.9801,  1.005

In [15]:
# Create a matrix with random numbers between 0 and 1
r = torch.rand(4, 4)
print(r)

tensor([[0.7122, 0.8740, 0.2544, 0.6196],
        [0.7888, 0.0503, 0.4739, 0.1167],
        [0.7983, 0.1365, 0.7396, 0.9751],
        [0.2868, 0.5208, 0.9605, 0.6032]])


In [16]:
# Create a  matrix with random numbers taken from a normal distribution with mean 0 and variance 1
r2 = torch.randn(4, 4)
print(r2)
print(r2.dtype)

tensor([[ 1.3156, -1.6212, -1.8346,  0.0195],
        [-0.9402,  0.0286,  0.4508,  0.1132],
        [ 1.5541,  1.8297, -0.0993,  0.7341],
        [-0.8339, -0.8423, -0.4997,  1.6735]])
torch.float32


In [17]:
# Create an array of 5 random integers from values between 6 and 9 (exclusive of 10)
in_array = torch.randint(6, 10, (5,))
print(in_array)
print(in_array.dtype)

tensor([8, 6, 8, 7, 8])
torch.int64


In [18]:
# Create a 2D Array (or matrix) of size 3x3 filled with random integers from values between 6 and 9 (exclusive of 10)
in_array2 = torch.randint(6, 10, (3,3))
print(in_array2)

tensor([[9, 8, 6],
        [9, 7, 7],
        [9, 7, 7]])


In [19]:
# Get the number of elements in in_array
print(torch.numel(in_array))

# Get the number of elements in in_array
print(torch.numel(in_array2))

5
9


In [20]:
# Construct a 3x3 matrix of zeros and dtpye long
z = torch.zeros(3, 3, dtype=torch.long)
print(z)

# Construct a 3x3 matrix of ones
o = torch.ones(3, 3)
print(o)
print(o.dtype)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [21]:
r2_like = torch.randn_like(r2, dtype=torch.double)  # Corvert the data type of the ternsor
print(r2_like)

tensor([[ 0.0965,  0.3901,  0.9554,  0.0543],
        [-0.0348, -0.0925,  0.4544, -0.5899],
        [-0.4634, -1.2394, -1.4591, -0.2900],
        [-1.4893, -0.1473,  1.3763, -1.5981]], dtype=torch.float64)


In [22]:
add_result = torch.add(r, r2)
print(add_result)

tensor([[ 2.0278, -0.7471, -1.5802,  0.6391],
        [-0.1514,  0.0788,  0.9247,  0.2299],
        [ 2.3524,  1.9663,  0.6403,  1.7092],
        [-0.5471, -0.3215,  0.4608,  2.2768]])


In [23]:
# In-place addition (change the value of r2)
r2.add_(r)      # re = torch.add(r, r2)
print(r2)

tensor([[ 2.0278, -0.7471, -1.5802,  0.6391],
        [-0.1514,  0.0788,  0.9247,  0.2299],
        [ 2.3524,  1.9663,  0.6403,  1.7092],
        [-0.5471, -0.3215,  0.4608,  2.2768]])


In [34]:
print(r2[:,1])   # all rows in column 1
print('\n')

print(r2[:,:2])  # all rows from column 0 to before column 2
print('\n')

print(r2[:3,:])  # take row 0 to before row 3 and all columns
print('\n')

num_ten = r2[2, 3]
print(num_ten)

print('\n')
print(num_ten.item())

print('\n')
print(r2[2,:])

tensor([-0.7471,  0.0788,  1.9663, -0.3215])


tensor([[ 2.0278, -0.7471],
        [-0.1514,  0.0788],
        [ 2.3524,  1.9663],
        [-0.5471, -0.3215]])


tensor([[ 2.0278, -0.7471, -1.5802,  0.6391],
        [-0.1514,  0.0788,  0.9247,  0.2299],
        [ 2.3524,  1.9663,  0.6403,  1.7092]])


tensor(1.7092)


1.7091888189315796


tensor([2.3524, 1.9663, 0.6403, 1.7092])


## Numpy Bridge

In [25]:
import numpy as np

In [26]:
# Converting a Torch Tensor to a NumPy Array
a = torch.ones(5)
print(a)
print('\n')

b = a.numpy()
print(b)
print('\n')

# See how the numpy array changed their value
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [27]:
# Converting NumPy  array  to Torch Tensor
# Observe the automatic changes of np array to torch tensor
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)  # add with inplace operation
print(a)
print('\n')

print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [28]:
# Move the tensor to the GPU
#r2 = r2.cuda()
#print(r2)

In [29]:
# Provide Easy switching between CPU & GPU
CUDA = torch.cuda.is_available()
print(CUDA)
if CUDA:
    add_result = add_result.cuda()
    print(add_result)

False


In [30]:
# You can also convert a list to a tensor
a = [2, 3, 4, 1]
to_list = torch.tensor(a)
print(to_list, to_list.dtype)

tensor([2, 3, 4, 1]) torch.int64


In [31]:
data = [[1., 2.], [3.,4.],
       [5., 6.], [7.,8.]]
T = torch.tensor(data)
print(T, T.dtype)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]]) torch.float32


## Tensor concatanation

In [32]:
# Tensor Concatanation
first_1 = torch.randn(2, 5)
print(first_1)
print('\n')

second_1 = torch.randn(3, 5)
print(second_1)
print('\n')

# Concatanation along the 0 dimension (concatanation rows)
con_1 = torch.cat([first_1, second_1])
print(con_1)
print('\n')

first_2 = torch.randn(2, 3)
print(first_2)
print('\n')

second_2 = torch.randn(2, 5)
print(second_2)
print('\n')

# Concatanation along the 1 dimension (concatanation columns)
con_2 = torch.cat([first_2, second_2], 1)
print(con_2)

tensor([[-0.0292, -0.5423, -0.8859,  2.5670, -1.2071],
        [-1.7902, -0.6800, -1.5927, -0.3746, -1.1699]])
tensor([[ 0.6158, -0.4763, -0.9881,  1.5266,  0.0741],
        [ 0.8542, -0.7245,  3.3269,  0.4473,  1.0172],
        [ 1.7461, -0.1926, -0.6880, -0.0084,  0.6699]])


tensor([[-0.0292, -0.5423, -0.8859,  2.5670, -1.2071],
        [-1.7902, -0.6800, -1.5927, -0.3746, -1.1699],
        [ 0.6158, -0.4763, -0.9881,  1.5266,  0.0741],
        [ 0.8542, -0.7245,  3.3269,  0.4473,  1.0172],
        [ 1.7461, -0.1926, -0.6880, -0.0084,  0.6699]])


tensor([[ 0.0113,  1.1441, -1.0468],
        [-0.1878, -0.6146,  0.7569]])
tensor([[ 0.0216,  0.4186,  0.0483, -0.5581,  1.2234],
        [-0.5212, -1.1098,  0.1678, -0.2149, -0.1605]])


tensor([[ 0.0113,  1.1441, -1.0468,  0.0216,  0.4186,  0.0483, -0.5581,  1.2234],
        [-0.1878, -0.6146,  0.7569, -0.5212, -1.1098,  0.1678, -0.2149, -0.1605]])


## Adding dimensions to tensors

In [33]:
tensor_1 = torch.tensor([1, 2, 3, 4])
tensor_a = torch.unsqueeze(tensor_1, 0)
print(tensor_a)
print(tensor_a.shape)
print('\n')

tensor_b = torch.unsqueeze(tensor_1, 1)
print(tensor_b)
print(tensor_b.shape)
print('\n')

tensor_2 = torch.rand(2, 3, 4)  # 2 is channels, 3 is the rows and 4 is the columns
print(tensor_2)
print('\n')

tensor_c = tensor_2[:, :, 2]
print(tensor_c)
print(tensor_c.shape)
print('\n')

tensor_d = torch.unsqueeze(tensor_c, 2)
print(tensor_d)
print(tensor_d.shape)

tensor([[1, 2, 3, 4]])
torch.Size([1, 4])


tensor([[1],
        [2],
        [3],
        [4]])
torch.Size([4, 1])


tensor([[[0.3634, 0.0521, 0.9295, 0.2416],
         [0.8777, 0.4527, 0.3606, 0.9494],
         [0.6880, 0.0200, 0.9909, 0.6272]],

        [[0.4869, 0.7745, 0.5151, 0.5053],
         [0.2956, 0.7622, 0.5482, 0.0478],
         [0.2631, 0.9833, 0.9441, 0.2590]]])


tensor([[0.9295, 0.3606, 0.9909],
        [0.5151, 0.5482, 0.9441]])
torch.Size([2, 3])


tensor([[[0.9295],
         [0.3606],
         [0.9909]],

        [[0.5151],
         [0.5482],
         [0.9441]]])
torch.Size([2, 3, 1])


## AutoGrad